# https://artifacthub.io/packages/helm/prometheus-community/kube-state-metrics
# helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
# helm install my-kube-state-metrics prometheus-community/kube-state-metrics --version 5.x
name: kube-state-metrics
version: 0.1.0
dependencies:
  - name: kube-state-metrics
    version: 5.x
    repository: https://prometheus-community.github.io/helm-charts
