---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: experimental-infra
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/kingphil/argocd-autopilot-draft.git
        revision: main
        files:
          - path: clusters/experimental/**/config_dir.yaml
  template:
    metadata:
      name: experimental-infra-{{ .userGivenName }}
      namespace: argocd
    spec:
      source:
        repoURL: '{{ .srcRepoURL }}'
        path: '{{ .path.path }}'
        targetRevision: '{{ .srcTargetRevision }}'
        directory:
          recurse: true
          exclude: '{{ .path.filename }}'
          include: '*.yaml'
      destination:
        namespace: '{{ .destNamespace }}'
        server: '{{ .destServer }}'
      project: experimental
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
