apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd.argoproj.io/sync-options: PruneLast=true
    argocd.argoproj.io/sync-wave: "-2"
  name: experimental
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: experimental project
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'
status: {}

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  creationTimestamp: null
  name: experimental
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      files:
      - path: clusters/experimental/**/config.yaml
      repoURL: https://github.com/kingphil/argocd-autopilot-draft.git
      revision: main
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      labels:
        app.kubernetes.io/name: '{{ .appName }}'
      name: experimental-{{ .userGivenName }}
      namespace: argocd
    spec:
      destination:
        namespace: '{{ .destNamespace }}'
        server: '{{ .destServer }}'
      project: experimental
      source:
        path: '{{ .srcPath }}'
        repoURL: '{{ .srcRepoURL }}'
        targetRevision: '{{ .srcTargetRevision }}'
        helm:
          valueFiles:
          - values.yaml
          ## note the prepended slash, as this is not relative to source.path above
          - /{{ .path.path }}/values.yaml
          ignoreMissingValueFiles: false
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
