---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: experimental-helm-plus
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/kingphil/argocd-autopilot-draft.git
        revision: main
        files:
          - path: clusters/experimental/**/config-helm+.yaml
  template:
    metadata:
      name: experimental-{{ .userGivenName }}
      namespace: argocd
    spec:
      sources:
      - repoURL: '{{ .srcRepoURL }}'
        path: '{{ .srcPath }}'
        targetRevision: '{{ .srcTargetRevision }}'
        helm:
          valueFiles:
            - values.yaml
            ## note the prepended slash, as this is not relative to source.path above
            - /{{ .path.path }}/values.yaml
          ignoreMissingValueFiles: true
      - repoURL: https://github.com/kingphil/argocd-autopilot-draft.git
        path: '{{ .path.path }}/manifests/'
        targetRevision: main
      destination:
        namespace: '{{ .destNamespace }}'
        server: '{{ .destServer }}'
      project: experimental
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
