appName: arc-pekware
userGivenName: arc-pekware
destNamespace: arc-pekware
destServer: https://kubernetes.default.svc
srcPath: charts/arc-runners/
srcRepoURL: https://github.com/kingphil/argocd-autopilot-draft.git
