gha-runner-scale-set:
  githubConfigUrl: "https://github.com/pekware"
  githubConfigSecret: pre-defined-secret
  minRunners: 1
  maxRunners: 10

  runnerGroup: pekware-on-prem

  containerMode:
    type: dind
  controllerServiceAccount:
    name: arc-systems-gha-rs-controller
    namespace: arc-systems
