version: '3'

tasks:
  kind-create:
    desc: Create kind development cluster
    cmds:
      - kind create cluster --name lab --kubeconfig $HOME/.kube/kind --config misc/kind/kind.yaml

  kind-delete:
    desc: Delete kind development cluster
    cmds:
      - KUBECONFIG=$HOME/.kube/kind kind delete cluster --name lab
      - rm -f $HOME/.kube/kind

  cilium-install:
    desc: Helm install of cilium to current K8s context
    cmds:
      - helm repo add cilium https://helm.cilium.io/
      - helm dep update examples/cilium/
      - helm install cilium examples/cilium/ -n kube-system
