version: '3'

tasks:
  kind-create:
    desc: Create kind development cluster
    cmds:
      - kind create cluster --name lab --kubeconfig $HOME/.kube/kind --config misc/kind/kind.yaml

  kind-delete:
    desc: Delete kind development cluster
    cmds:
      - KUBECONFIG=$HOME/.kube/kind kind delete cluster --name lab
      - rm -f $HOME/.kube/kind

  cilium-install:
    desc: Helm install of cilium to current K8s context
    cmds:
      - helm repo add cilium https://helm.cilium.io/
      - helm dep update examples/cilium/
      - helm install --wait cilium examples/cilium/ -n kube-system

  argocd-bootstrap:
    desc: Helm "bootstrap" install of argocd
    vars:
      CONTEXT: '{{default "development" .CONTEXT}}'
    cmds:
      - helm repo add argo-helm https://argoproj.github.io/argo-helm
      - helm dep update apps/argocd/
      - helm install --wait {{.CONTEXT}}-argocd apps/argocd/ -n argocd --create-namespace --values clusters/{{.CONTEXT}}/argocd/values.yaml
      - kubectl create -f $HOME/povault/k8s-secrets/{{.CONTEXT}} || /bin/true
      - kubectl create -f clusters/{{.CONTEXT}}/

  kind-install:
    desc: Install kind
    cmds:
      - |
        (
          cd "$(mktemp -d)" &&
          OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
          ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
          KIND="kind-${OS}-${ARCH}" &&
          curl -fsSLO "https://github.com/kubernetes-sigs/kind/releases/latest/download/${KIND}" &&
          sudo install -o root -g root -m 0755 $KIND /usr/local/bin/kind
        )
