ingress-nginx:
  controller:
    ingressClassResource:
      default: true

    kind: Deployment
    replicaCount: 1

    service:
      enabled: false

    extraArgs:
      default-ssl-certificate: "kube-system/star.pekware.club"

    hostNetwork: true
    hostPort:
      enabled: false

    nodeSelector:
      ingress-ready: "true"
    tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
