kubernetes_version: v1.31.4
cluster_name: capi-do-kubeadm
region: nyc1

control_plane_machine_image: ""
control_plane_machine_count: 1
control_plane_machine_type: s-2vcpu-2gb

worker_machine_image: ""
worker_machine_count: 1
worker_machine_type: s-2vcpu-2gb

ssh_key_fingerprint: ""

## for quoting reasons; only override these if you know what you are doing
instance_id: '{{ ds.meta_data["instance_id"] }}'
local_hostname_dict: '{{ ds.meta_data["local_hostname"] }}'
local_hostname_attr: '{{ ds.meta_data.local_hostname }}'
