---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: "{{ .Values.cluster_name }}"
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["192.168.0.0/16"]
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: DOCluster
    name: "{{ .Values.cluster_name }}"
  controlPlaneRef:
    kind: KubeadmControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    name: "{{ .Values.cluster_name }}-control-plane"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DOCluster
metadata:
  name: "{{ .Values.cluster_name }}"
spec:
  region: {{ .Values.region }}
---
kind: KubeadmControlPlane
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
metadata:
  name: "{{ .Values.cluster_name }}-control-plane"
spec:
  replicas: {{ .Values.control_plane_machine_count }}
  machineTemplate:
    infrastructureRef:
      kind: DOMachineTemplate
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      name: "{{ .Values.cluster_name }}-control-plane"
  kubeadmConfigSpec:
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
          provider-id: digitalocean://'{{ .Values.instance_id }}'
        name: '{{ .Values.local_hostname_dict }}'
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
        name: '{{ .Values.local_hostname_dict }}'
  version: "{{ .Values.kubernetes_version }}"
---
kind: DOMachineTemplate
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
metadata:
  name: "{{ .Values.cluster_name }}-control-plane"
spec:
  template:
    spec:
      size: "{{ .Values.control_plane_machine_type }}"
      image: {{ .Values.control_plane_machine_image }}
      sshKeys:
        - {{ .Values.ssh_key_fingerprint }}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: "{{ .Values.cluster_name }}-md-0"
spec:
  clusterName: "{{ .Values.cluster_name }}"
  replicas: {{ .Values.worker_machine_count }}
  selector:
    matchLabels:
  template:
    spec:
      clusterName: "{{ .Values.cluster_name }}"
      version: "{{ .Values.kubernetes_version }}"
      bootstrap:
        configRef:
          name: "{{ .Values.cluster_name }}-md-0"
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
      infrastructureRef:
        name: "{{ .Values.cluster_name }}-md-0"
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: DOMachineTemplate
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DOMachineTemplate
metadata:
  name: "{{ .Values.cluster_name }}-md-0"
spec:
  template:
    spec:
      size: "{{ .Values.worker_machine_type }}"
      image: {{ .Values.worker_machine_image }}
      sshKeys:
        - {{ .Values.ssh_key_fingerprint }}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: "{{ .Values.cluster_name }}-md-0"
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          name: '{{ .Values.local_hostname_attr }}'
          kubeletExtraArgs:
            cloud-provider: external
