rollOutCiliumPods: true

# https://docs.cilium.io/en/stable/network/concepts/routing/#native-routing
routingMode: native
autoDirectNodeRoutes: true
ipv4NativeRoutingCIDR: 172.16.0.0/12

ipam:
  operator:
    clusterPoolIPv4PodCIDRList:
      - 172.17.1.0/24
    clusterPoolIPv4MaskSize: 24

kubeProxyReplacement: true
#k8sServiceHost: 172.16.0.53  ## haproxy (for k3s-home-ha cluster)
k8sServiceHost: 172.16.0.54  ## k3s-single
k8sServicePort: 6443

bgpControlPlane:
  enabled: true

ingressController:
  enabled: true
  default: true
  loadbalancerMode: shared
  defaultSecretNamespace: kube-system
  defaultSecretName: star.demo.codemonkeys.site

operator:
  replicas: 1

hubble:
  relay:
    enabled: true
  ui:
    enabled: true
    ingress:
      enabled: true
      className: cilium
      hosts:
        - hubble-home.demo.codemonkeys.site
      tls:
        - hosts:
            - hubble-home.demo.codemonkeys.site
