rollOutCiliumPods: true

bgpControlPlane:
  enabled: true

ingressController:
  enabled: true
  default: true
  loadbalancerMode: shared
  defaultSecretNamespace: kube-system
  defaultSecretName: star.demo.codemonkeys.site
  service:
    insecureNodePort: 32080
    secureNodePort: 32443

nodePort:
  enabled: true

operator:
  replicas: 1

hubble:
  ui:
    enabled: true
    ingress:
      enabled: true
      className: cilium
      hosts:
        - hubble-home.demo.codemonkeys.site
      tls:
        - hosts:
            - hubble-home.demo.codemonkeys.site
