rollOutCiliumPods: true

bgpControlPlane:
  enabled: true

ingressController:
  enabled: true
  default: true
  loadbalancerMode: shared
  defaultSecretNamespace: kube-system
  defaultSecretName: star.demo.codemonkeys.site

nodePort:
  enabled: true

operator:
  replicas: 1
