appName: ingress-nginx
userGivenName: ingress-nginx
destNamespace: ingress-nginx
srcPath: charts/ingress-nginx
srcRepoURL: https://github.com/kingphil/argocd-autopilot-draft.git
srcTargetRevision: main
