apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io/foreground
  labels:
    app.kubernetes.io/name: root
  name: root
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/kingphil/argocd-autopilot-draft.git
    targetRevision: main
    path: clusters/development/cluster-resources/
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
    - allowEmpty=true
