# https://github.com/actions/actions-runner-controller
name: arc-runners
version: 0.1.0
dependencies:
  - name: gha-runner-scale-set
    version: 0.11.0
    repository: oci://ghcr.io/actions/actions-runner-controller-charts
