apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: development
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/kingphil/argocd-autopilot-draft.git
        revision: main
        files:
          - path: clusters/development/**/config.yaml
        template:
          metadata: {}  ## required
          spec:
            source:
              path: '{{ .srcPath }}'
              helm:
                valueFiles:
                  - values.yaml  ## global values file beside the relevant Chart.yaml
                  - /{{ .path.path }}/values.yaml  ## override values file beside the config.yaml
                ignoreMissingValueFiles: true
              repoURL: ""  ## required
            destination: {}  ## required
            project: ""  ## required
    - git:
        repoURL: https://github.com/kingphil/argocd-autopilot-draft.git
        revision: main
        files:
          - path: clusters/development/**/config-dir.yaml
        template:
          metadata: {}  ## required
          spec:
            source:
              path: '{{ .path.path }}'
              directory:
                recurse: true
                exclude: '{{ .path.filename }}'
                include: '*.yaml'
              repoURL: ""  ## required
            destination: {}  ## required
            project: ""  ## required
  syncPolicy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: '{{ .appName }}'
      name: '{{ .userGivenName }}-development'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io/foreground
    spec:
      source:
        repoURL: '{{ .srcRepoURL }}'
        targetRevision: main
      destination:
        namespace: '{{ .destNamespace }}'
        server: '{{ .destServer }}'
      project: development
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
        managedNamespaceMetadata:
          ## so the deletion of the App also removes the namespace it creates
          ## https://github.com/argoproj/argo-cd/issues/7875
          labels:
            argocd.argoproj.io/instance: '{{ .userGivenName }}-development'
