kubernetes_version: v1.31.4
cluster_name: pek-20250313

# 180665624: "Cluster API Kubernetes v1.31.4 on Ubuntu 24.04"
control_plane_machine_image: 180665624

worker_machine_image: 180665624
worker_machine_count: 2

ssh_key_fingerprint: "24:85:01:a1:3b:87:10:8e:69:f3:30:ce:8a:f3:89:ec"
