appName: argocd
userGivenName: argocd
destNamespace: argocd
destServer: https://kubernetes.default.svc
srcPath: charts/argocd
srcRepoURL: https://github.com/kingphil/argocd-autopilot-draft.git
srcTargetRevision: main
