global:
  domain: argocd-home.demo.codemonkeys.site
configs:
  cm:
    timeout.reconciliation: 10s  ## DEVEL
    kustomize.buildOptions: "--enable-helm --load-restrictor=LoadRestrictionsNone"
  ## https://artifacthub.io/packages/helm/argo/argo-cd#ssl-termination-at-ingress-controller
  params:
    server.insecure: true
server:
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    extraTls:
      - hosts:
        - argocd-home.demo.codemonkeys.site
